# Generated by Django 2.2.16 on 2026-01-30 03:50

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.metadata.archives.fields
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0030_video_giphy_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictureoftheweek',
            options={'ordering': ('-release_date',), 'permissions': [('view_only_non_default', 'Can view only non default language')], 'verbose_name_plural': 'Pictures of the Month'},
        ),
        migrations.AlterModelOptions(
            name='pictureoftheweekproxy',
            options={'verbose_name': 'Pictures of the Month translation'},
        ),
        migrations.AddField(
            model_name='pictureoftheweek',
            name='category',
            field=models.CharField(choices=[('POTW', 'Picture of the Week'), ('POTM', 'Picture of the Month')], default='POTM', help_text='Category: Picture of the Week or Month', max_length=4, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='media.Image', verbose_name='Translation source'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=djangoplicity.metadata.archives.fields.AVMTypeField(blank=True, choices=(('Observation', 'Observation'), ('Artwork', 'Artwork'), ('Photographic', 'Photographic'), ('Planetary', 'Planetary'), ('Simulation', 'Simulation'), ('Collage', 'Collage'), ('Chart', 'Chart')), help_text='The type of image/media resource.', max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='web_category',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(type__name='Images'), to='metadata.Category'),
        ),
        migrations.AlterField(
            model_name='imagecomparison',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='media.ImageComparison', verbose_name='Translation source'),
        ),
        migrations.AlterField(
            model_name='pictureoftheweek',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='media.PictureOfTheWeek', verbose_name='Translation source'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='media.Video', verbose_name='Translation source'),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=djangoplicity.metadata.archives.fields.AVMTypeField(blank=True, choices=(('Observation', 'Observation'), ('Artwork', 'Artwork'), ('Photographic', 'Photographic'), ('Planetary', 'Planetary'), ('Simulation', 'Simulation'), ('Collage', 'Collage'), ('Chart', 'Chart')), help_text='The type of image/media resource.', max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='web_category',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(type__name='Videos'), to='metadata.Category'),
        ),
    ]
