# Generated by Django 2.2.16 on 2026-01-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0031_auto_20260130_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureoftheweek',
            name='category',
            field=models.CharField(choices=[('POTW', 'Picture of the Week'), ('POTM', 'Picture of the Month')], default='POTW', help_text='Category: Picture of the Week or Month', max_length=4, verbose_name='Category'),
        ),
    ]
